Allows setting/resetting `entity.rgb` to `None`
mozman/ezdxf pull request #1116
Opened 2024-06-26 05:40 UTC by kkkkkom

Hi, @mozman , could you please review this minor merge request?

I think we should allow `entity.rgb` to be set/reset to `None`.

Many entity rgbs are initially `None` by default, and this change will allow users/developers to temporarily set rgb and reset it back without causing an error.

2024-06-26 06:17 UTC, mozman requested changes
This is not the correct way.

If you rally need this feature implement the `@rgb.deleter` method and check if the attrib `true_color`  exists otherwise a `DXFAttributeError` will be raised.

2024-06-26 23:18 UTC, kkkkkom commented
> This is not the correct way.
> 
> If you rally need this feature implement the `@rgb.deleter` method and check if the attrib `true_color` exists otherwise a `DXFAttributeError` will be raised.

Thanks for reviewing, I'll update accordingly

2024-06-26 23:37 UTC, kkkkkom commented
Hi, @mozman , could you please review again?

2024-06-27 04:22 UTC, mozman commented on src/ezdxf/entities/dxfgfx.py
> +        if rgb is None:
This case should raise a TypeError, None is not a valid input or revert everything because the previous version raised the TypeError automatically.

2024-06-27 06:10 UTC, mozman commented
@kkkkkom  thanks for the idea, to speed up the process I added all the necessary changes myself

2024-06-27 06:10 UTC, closed without merging

2024-06-27 06:30 UTC, kkkkkom commented
> @kkkkkom thanks for the idea, to speed up the process I added all the necessary changes myself

Thanks!